trigger:
  branches:
    include:
      - feature

# Use our self-hosted Windows agent
pool:
  name: sep-agent

stages:
  - stage: CI
    jobs:
      - job: feature_job
        displayName: "Feature CI"
        steps:
          - task: TerraformInstaller@1
            displayName: "Terraform Install"
            inputs:
              terraformVersion: '1.11.4'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
              backendServiceArm: 'sc-azure-terraform'
              backendAzureRmStorageAccountName: 'storegoyal1121'
              backendAzureRmContainerName: 'contstore'
              backendAzureRmKey: 'microservice-infra-dev.tfstate'
          - task: TerraformTask@5
            displayName: terraform_fmt
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              commandOptions: '-check -recursive'
              outputTo: 'console'
              customCommand: 'fmt'
              environmentServiceNameAzureRM: 'sc-azure-terraform'

          - task: TerraformTask@5
            displayName: terraform_validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          
          - task: TerraformTask@5

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
              environmentServiceNameAzureRM: 'sc-azure-terraform'